import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { MetaMailLogo } from "@/components/metamail-logo";

const faqs = [
  {
    q: "Can I send and receive emails from other mailboxes (Gmail, Outlook, etc.)?",
    a: "Of course! One of our visions is to connect Web2 and Web3 users without boundaries.",
  },
  {
    q: "Free to use?",
    a: "Yes! MetaMail is totally free and without gas fees. Furthermore, MetaMail will not charge you any fees during your use.",
  },
  {
    q: "Need to register?",
    a: "No. Just connect your wallet with our website.",
  },
  {
    q: "Why need a signature when logging in? Will my wallet's private key be leaked in this step?",
    a: "To verify the ownership of your address, you need to sign with your wallet's private key. It's safe to sign the message. MetaMail calls the wallet interface for signature without revealing the wallet's private key, and the step is also free (without a gas fee).",
  },
  {
    q: "Why do I need to have a non-zero ETH balance or nonce in my wallet when logging in?",
    a: "A non-zero ETH balance or nonce in the address proves this address has some on-chain activities in history. This is a temporary POS-like mechanism to prevent robots from registering large numbers of addresses. We will consider other mechanisms in the future to verify the validity of an address.",
  },
  {
    q: "How to get an email address with ENS?",
    a: 'A tutorial for registering ENS: <a href="https://support.ens.domains/en/articles/7882582-how-to-register" target="_blank" rel="noopener noreferrer" class="text-primary underline">How to register ENS</a>',
  },
  {
    q: "I have registered an ENS, but it doesn't show up?",
    a: 'Make sure you have set the Primary ENS Name record: <a href="https://support.ens.domains/en/articles/7890756-the-primary-name" target="_blank" rel="noopener noreferrer" class="text-primary underline">The Primary name</a>. And just log in again.',
  },
  {
    q: "Where are mails stored?",
    a: "The mails are stored on our server. It is very secure because the signing and encryption of emails are completely done in the front end (the code is open-source).",
  },
  {
    q: "What are email signatures and end-to-end encryption?",
    a: "An email signature is a number generated by the sender of the email, which ensures the integrity of the email and identifies the sender of the email (preventing impersonation). End-to-end encryption means that the sender encrypts the email's content with a symmetric encryption key, which is then encrypted with the recipient's public key. The recipient uses their private key to decrypt the symmetric key and subsequently decrypts the email content with it. This ensures that no one else, except the sender and recipient, can access the content of the email.",
  },
  {
    q: "I transferred my ENS to others, will my historical emails be seen by others?",
    a: "Absolutely not! Each time your ENS mailbox sends or receives an email, it is stored in the inbox associated with your unique ETH address. When the ENS is linked to a new address, emails received after that point are directed to the new address's inbox. Emails received before the transfer will not be visible in the new inbox. Additionally, your private keys related to MetaMail, derived from your wallet's private key, remain securely with you. The content of your emails cannot be decrypted even if others obtain the emails through other means.",
  },
];

export default function FAQsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 items-center gap-4 px-4 md:px-6">
          <Link href="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            <MetaMailLogo size={24} />
            <span className="font-bold">MetaMail</span>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 md:px-6 py-12 max-w-3xl">
        <h1 className="text-3xl font-bold mb-2">Frequently Asked Questions</h1>
        <p className="text-muted-foreground mb-10">
          Everything you need to know about MetaMail.
        </p>

        <div className="space-y-6">
          {faqs.map((faq, i) => (
            <div key={i} className="rounded-lg border p-6">
              <h2 className="font-semibold text-lg mb-3">{faq.q}</h2>
              <p
                className="text-muted-foreground leading-relaxed"
                dangerouslySetInnerHTML={{ __html: faq.a }}
              />
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-lg border bg-muted/30 p-6 text-center">
          <p className="text-sm text-muted-foreground">
            Have more questions? Contact us at{" "}
            <a href="mailto:metamail@mmail.ink" className="text-primary underline">
              metamail@mmail.ink
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}
